import { cssColorNames } from "@packages/parse-css"; // TODO: Add color functions
import { cssProperties } from "./cssProperties";

const common = ["inherit", "initial", "unset", "var()"];
const commonAlign = [
  "baseline",
  "center",
  "end",
  "first baseline",
  "flex-end",
  "flex-start",
  "last baseline",
  "normal",
  "safe",
  "self-end",
  "start",
  "stretch",
  "unsafe",
  ...common,
];
const cubic = [
  "cubic-bezier()",
  "cubic-bezier(0.075, 0.82, 0.165, 1)",
  "cubic-bezier(0.165, 0.84, 0.44, 1)",
  "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
  "cubic-bezier(0.19, 1, 0.22, 1)",
  "cubic-bezier(0.215, 0.610, 0.355, 1)",
  "cubic-bezier(0.23, 1, 0.320, 1)",
  "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
  "cubic-bezier(0.39, 0.575, 0.565, 1)",
  "cubic-bezier(0.445, 0.05, 0.55, 0.95)",
  "cubic-bezier(0.455, 0.03, 0.515, 0.955)",
  "cubic-bezier(0.47, 0, 0.745, 0.715)",
  "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
  "cubic-bezier(0.55, 0.085, 0.68, 0.53)",
  "cubic-bezier(0.6, -0.28, 0.735, 0.045)",
  "cubic-bezier(0.645, 0.045, 0.355, 1)",
  "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
  "cubic-bezier(0.755, 0.05, 0.855, 0.06)",
  "cubic-bezier(0.77, 0, 0.175, 1)",
  "cubic-bezier(0.785, 0.135, 0.15, 0.86)",
  "cubic-bezier(0.86, 0, 0.07, 1)",
  "cubic-bezier(0.895, 0.03, 0.685, 0.22)",
  "cubic-bezier(0.95, 0.05, 0.795, 0.035)",
  "cubic-bezier(1, 0, 0, 1)",
];
const animationFillMode = ["backwards", "both", "none", ...common];
const animationDirection = ["alternate", "alternate-reverse", "normal", "reverse"];
const animation = [
  "backwards",
  "both",
  "forwards",
  "infinite",
  "ease",
  "ease-in",
  "ease-in-out",
  "ease-out",
  "linear",
  "step-end",
  "step-start",
  "steps()",
  ...animationDirection,
  ...animationFillMode,
];
const backgroundFunctions = [
  "-moz-element()",
  "-moz-linear-gradient()",
  "-moz-radial-gradient()",
  "-moz-repeating-linear-gradient()",
  "-moz-repeating-radiaul-gradient()",
  "-o-linear-gradient()",
  "-o-repeating-linear-gradient()",
  "-webkit-gradient()",
  "-webkit-image-set()",
  "-webkit-linear-gradient()",
  "-webkit-radial-gradient()",
  "-webkit-repeating-linear-gradient()",
  "-webkit-repeating-radiaul-gradient()",
  "calc()",
  "cross-fade()",
  "element()",
  "image()",
  "image-set()",
  "linear-gradient()",
  "radial-gradient",
  "repeating-linear-gradient()",
  "repeating-radial-gradient()",
  "url()",
  ...common,
];
// 0ms, 0s
const numeric = ["calc()", ...common];
const borderWidth = ["medium", "thick", "thin", ...numeric];
const borderStyle = [
  "dashed",
  "dotted",
  "double",
  "groove",
  "hidden",
  "inset",
  "none",
  "outset",
  "ridge",
  "solid",
  ...common,
];
const borderOptions = [...cssColorNames, ...borderStyle]; // auto complete to numeric
const xAxisPosition = ["left", "right"];
const yAxisPosition = ["bottom", "top"];
const commonBackground = ["border-box", "content-box"];
const paddingCommonBackground = [...commonBackground, "padding-box"];
const commonImage = ["repeat", "round", "space", "stretch"];
const commonBreak = [
  "always",
  "auto",
  "avoid",
  "avoid-column",
  "avoid-page",
  "column",
  "left",
  "page",
  "right",
  ...common,
];
const counter = ["none", ...numeric];
const visibility = ["hidden", "visible"];
const commonFlex = ["auto", "content"];
const flexDirection = ["column", "column-reverse", "row", "row-reverse"];
const flexWrap = ["nowrap", "wrap", "wrap-reverse"];
const commonRule = ["evenodd", "nonzero", ...common];
const commonAutoNone = ["auto", "none", ...common];
const gridAuto = ["min-content", "max-content", "auto", "minmax()", ...numeric];
const gridTemplate = ["none", "subgrid", "repeat()", ...gridAuto];
const autoNumeric = ["auto", ...numeric];
const commonGrid = ["span", ...autoNumeric];
const commonJustify = [
  "auto",
  "normal",
  "end",
  "start",
  "flex-end",
  "flex-start",
  "self-end",
  "self-start",
  "center",
  "left",
  "right",
  "baseline",
  "first baseline",
  "last baseline",
  "stretch",
];
const normalNumeric = ["normal", ...numeric];
const listStyle = [
  "armenian",
  "circle",
  "decimal",
  "decimal-leading-zero",
  "disc",
  "georgian",
  "lower-alpha",
  "lower-greek",
  "lower-latin",
  "lower-roman",
  "none",
  "square",
  "symbols()",
  "upper-alpha",
  "upper-latin",
  "upper-roman",
  ...common,
];
const listStylePosition = ["inside", "outside"];
const noneBackgroundFunctions = ["none", ...backgroundFunctions];
const size = ["fit-content", "max-content", "min-content", ...numeric];
const heightWidth = ["auto", ...size];
const maxSize = ["none", ...size];
const marker = ["none", "url()", ...common];
const motion = [
  "none",
  "path()",
  "reverse",
  "circle()",
  "ellipse()",
  "fill-box",
  "margin-box",
  "polygon()",
  "stroke-box",
  "view-box",
  ...autoNumeric,
];
const nav = ["auto", "current", "root", ...common];
const overflow = ["auto", "hidden", "scroll", "visible", ...common];
const overflowClip = ["clip", ...overflow];
const position = ["center", ...yAxisPosition, ...xAxisPosition, ...common];
const commonAutoNoneClip = ["contain", ...commonAutoNone];
const transitionTiming = [
  "all",
  "none",
  ...cubic,
  "ease",
  "ease-in",
  "ease-in-out",
  "ease-out",
  "linear",
  "step-end",
  "step-start",
  "steps()",
  ...common,
];
const animationIterationCount = ["infinite", ...numeric];
const transform = [
  "matrix()",
  "matrix3d()",
  "none",
  "perspective()",
  "rotate()",
  "rotate3d()",
  "rotateX('angle')",
  "rotateY('angle')",
  "rotateZ('angle')",
  "scale()",
  "scale3d()",
  "scaleX()",
  "scaleY()",
  "scaleZ()",
  "skew()",
  "skewX()",
  "skewY()",
  "translate()",
  "translate3d()",
  "translateX()",
  "translateY()",
  "translateZ()",
  ...common,
];
const zoom = ["normal", ...numeric];
const webkitCommonBreak = [
  "always",
  "auto",
  "avoid",
  "avoid-column",
  "avoid-page",
  "avoid-region",
  "column",
  "left",
  "page",
  "region",
  "right",
  ...common,
];
const webkitCommonBreakInside = [
  "auto",
  "avoid",
  "avoid-column",
  "avoid-page",
  "avoid-region",
  ...common,
];
const filter = [
  "blur()",
  "brightness()",
  "contrast()",
  "drop-shadow()",
  "grayscale()",
  "hue-rotate()",
  "invert()",
  "none",
  "opacity()",
  "saturate()",
  "sepia()",
  "url()",
  ...common,
];
const hyphens = ["auto", "manual", "none", ...common];
const marginCollapse = ["collapse", "discard", "separate", ...common];

export const cssValues: Record<(typeof cssProperties)[number], readonly string[] | string[]> = {
  // "align-self: start;": [],
  "align-items": commonAlign,
  animation,
  "align-self": commonAlign,
  "animation-timing-function": animation,
  appearance: common,
  "animation-duration": numeric,
  "animation-name": common,
  "align-content": ["space-around", "space-between", "space-evenly", ...commonAlign],
  "animation-delay": numeric,
  "animation-iteration-count": animationIterationCount,
  "animation-fill-mode": ["forwards", ...animationFillMode],
  "aspect-ratio": common,
  "animation-direction": [...animationDirection, ...common],
  all: common,
  "animation-play-state": ["paused", "running", ...common],
  "accent-color": common,
  "additive-symbols": backgroundFunctions,
  "alignment-baseline": [
    "alphabetic",
    "baseline",
    "central",
    "ideographic",
    "mathematical",
    "middle",
    "text-after-edge",
    "text-before-edge",
    ...common,
  ],
  alt: common,
  "anchor-name": common,
  "anchor-scope": common,
  "animation-composition": common,
  "animation-range": common,
  "animation-range-end": common,
  "animation-range-start": common,
  "animation-timeline": common,
  "ascent-override": common,
  bottom: autoNumeric,
  border: borderOptions,
  "background-color": cssColorNames,
  background: ["fixed", "local", "none", "scroll", ...backgroundFunctions, ...cssColorNames],
  "border-radius": common,
  "box-sizing": [...commonBackground, ...common],
  "box-shadow": ["inset", "none", "color()", "color-mix()", ...cssColorNames],
  "background-image": backgroundFunctions,
  "background-position": position,
  "border-bottom": borderOptions,
  "border-color": cssColorNames,
  "background-repeat": ["no-repeat", "repeat", "repeat-x", "repeat-y", "round", "space", ...common],
  "background-size": ["auto", "contain", "cover", ...common],
  "border-top": borderOptions,
  "border-width": borderWidth,
  "border-left": borderOptions,
  "border-right": borderOptions,
  "border-style": borderStyle,
  "border-bottom-left-radius": numeric,
  "border-bottom-right-radius": numeric,
  "border-top-left-radius": numeric,
  "border-top-right-radius": numeric,
  "border-collapse": ["collapse", "separate", ...common],
  "border-top-color": cssColorNames,
  "background-clip": [...paddingCommonBackground, ...common],
  "border-bottom-color": cssColorNames,
  "border-left-color": cssColorNames,
  "border-right-color": cssColorNames,
  "border-spacing": numeric,
  "border-left-width": borderWidth,
  "backdrop-filter": common,
  "border-right-width": borderWidth,
  "border-bottom-width": borderWidth,
  "border-top-width": borderWidth,
  "backface-visibility": [...visibility, ...common],
  "border-bottom-style": borderStyle,
  "background-position-x": ["center", ...xAxisPosition, ...common],
  "border-top-style": borderStyle,
  "background-attachment": ["fixed", "local", "scroll", ...common],
  "background-blend-mode": [
    "color",
    "color-burn",
    "color-dodge",
    "darken",
    "difference",
    "exclusion",
    "hard-light",
    "hue",
    "lighten",
    "luminosity",
    "multiply",
    "normal",
    "overly",
    "saturation",
    "screen",
    "soft-light",
    ...common,
  ],
  "background-position-y": ["center", ...yAxisPosition, ...common],
  "block-size": common,
  "border-end-end-radius": numeric,
  "border-end-start-radius": numeric,
  "border-left-style": borderStyle,
  "border-start-end-radius": numeric,
  "border-start-start-radius": numeric,
  "background-origin": [...paddingCommonBackground, ...common],
  "border-block-end": borderOptions,
  "border-block-start": borderOptions,
  "border-inline-end": borderOptions,
  "border-inline-start": borderOptions,
  "border-right-style": borderStyle,
  "border-image": ["auto", "fill", "none", ...commonImage, "url()", ...common],
  "border-block-end-width": numeric,
  "border-inline-end-width": numeric,
  "border-inline-start-width": numeric,
  "box-decoration-break": ["clone", "slice", ...common],
  "break-inside": ["auto", "avoid", "avoid-column", "avoid-page", ...common],
  "base-palette": common,
  "baseline-shift": common,
  behavior: common,
  bleed: common,
  "border-block": common,
  "border-block-color": common,
  "border-block-end-color": cssColorNames,
  "border-block-end-style": borderStyle,
  "border-block-start-color": cssColorNames,
  "border-block-start-style": borderStyle,
  "border-block-start-width": borderWidth,
  "border-block-style": common,
  "border-block-width": common,
  "border-image-outset": numeric,
  "border-image-repeat": [...commonImage, ...common],
  "border-image-slice": ["fill", ...common],
  "border-image-source": noneBackgroundFunctions,
  "border-image-width": numeric,
  "border-inline": common,
  "border-inline-color": common,
  "border-inline-end-color": cssColorNames,
  "border-inline-end-style": borderStyle,
  "border-inline-start-color": cssColorNames,
  "border-inline-start-style": borderStyle,
  "border-inline-style": common,
  "border-inline-width": common,
  "break-after": commonBreak,
  "break-before": commonBreak,
  color: cssColorNames,
  cursor: [
    "alias",
    "all-scroll",
    "auto",
    "cell",
    "col-resize",
    "content-menu",
    "copy",
    "crosshair",
    "default",
    "e-resize",
    "ew-resize",
    "grab",
    "grabbing",
    "help",
    "move",
    "n-resize",
    "ne-resize",
    "nesw-resize",
    "no-drop",
    "none",
    "not-allowed",
    "ns-resize",
    "nw-resize",
    "nwse-resize",
    "pointer",
    "progress",
    "row-resize",
    "s-resize",
    "se-resize",
    "sw-resize",
    "text",
    "vertical-text",
    "w-resize",
    "wait",
    "zoom-in",
    "zoom-out",
    "-moz-grab",
    "-moz-grabbing",
    "-moz-zoom-in",
    "-moz-zoom-out",
    "-webkit-grab",
    "-webkit-grabbing",
    "-webkit-zoom-in",
    "-webkit-zoom-out",
    ...common,
  ],
  content: ["attr()", "counter(name)", "icon", "none", "normal", "url()", ...common],
  clear: ["both", "left", "none", "right", ...common],
  "clip-path": [
    "none",
    "url()",
    "calc()",
    "circle()",
    "ellipse()",
    "fill-box",
    "inset()",
    "margin-box",
    "polygon()",
    "stroke-box",
    "view-box",
    ...common,
  ],
  "column-gap": normalNumeric,
  contain: ["content", "layout", "none", "paint", "size", "strict", "style", ...common],
  "color-scheme": common,
  "caret-color": cssColorNames,
  "counter-increment": counter,
  "counter-reset": counter,
  "column-count": autoNumeric,
  container: common,
  "caption-side": [...yAxisPosition, ...common],
  "container-type": common,
  "content-visibility": ["auto", ...visibility, ...common],
  "column-rule": borderOptions,
  "column-width": autoNumeric,
  columns: autoNumeric,
  cx: common,
  cy: common,
  caret: common,
  "caret-shape": ["auto", "bar", "block", "underscore", ...common],
  "clip-rule": commonRule,
  "color-interpolation-filters": ["auto", "linearRGB", "sRGB", ...common],
  "column-fill": ["auto", "balance", ...common],
  "column-rule-color": cssColorNames,
  "column-rule-style": borderStyle,
  "column-rule-width": borderWidth,
  "column-span": ["all", "none", ...common],
  "contain-intrinsic-block-size": numeric,
  "contain-intrinsic-height": numeric,
  "contain-intrinsic-inline-size": numeric,
  "contain-intrinsic-size": numeric,
  "contain-intrinsic-width": numeric,
  "container-name": common,
  "counter-set": common,
  d: numeric,
  display: [
    "block",
    "contents",
    "flex",
    "flexbox",
    "flow-root",
    "grid",
    "inline",
    "inline-block",
    "inline-flex",
    "inline-flexbox",
    "inline-table",
    "list-item",
    "none",
    "ruby",
    "ruby-base",
    "ruby-base-container",
    "ruby-text",
    "ruby-text-container",
    "run-in",
    "table",
    "table-caption",
    "table-cell",
    "table-column",
    "table-column-group",
    "table-footer-group",
    "table-header-group",
    "table-row",
    "table-row-group",
    "-moz-box",
    "-moz-deck",
    "-moz-grid",
    "-moz-grid-group",
    "-moz-grid-line",
    "-moz-groupbox",
    "-moz-inline-box",
    "-moz-inline-grid",
    "-moz-inline-stack",
    "-moz-marker",
    "-moz-popup",
    "-moz-stack",
    "-ms-flexbox",
    "-ms-grid",
    "-ms-inline-flexbox",
    "-ms-inline-grid",
    "-webkit-box",
    "-webkit-flex",
    "-webkit-inline-box",
    "-webkit-inline-flex",
    ...common,
  ],
  direction: ["ltr", "rtl", ...common],
  "descent-override": common,
  "dominant-baseline": [
    "alphabetic",
    "auto",
    "central",
    "hanging",
    "ideographic",
    "mathematical",
    "middle",
    "text-bottom",
    "text-top",
    ...common,
  ],
  "empty-cells": ["hide", "show", "-moz-show-background", ...common],
  "enable-background": ["accumulate", "new", ...common],
  "font-size": [
    "large",
    "larger",
    "medium",
    "small",
    "smaller",
    "x-large",
    "x-small",
    "xx-large",
    "xx-small",
    ...common,
  ],
  "font-family": [
    "'Courier New', Courier, monospace",
    "'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif",
    "'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif",
    "'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif",
    "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    "'Times New Roman', Times, serif",
    "'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif",
    "Arial, Helvetica, sans-serif",
    "Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
    "Georgia, 'Times New Roman', Times, serif",
    "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
    "Verdana, Geneva, Tahoma, sans-serif",
    "cursive",
    "fantasy",
    "monospace",
    "sans-serif",
    "serif",
    "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    ...common,
  ],
  "font-weight": [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "bold",
    "bolder",
    "lighter",
    "normal",
    ...common,
  ],
  "font-style": ["italic", "normal", "oblique", ...common],
  float: ["inline-end", "inline-start", "left", "none", "right", ...common],
  "flex-direction": [...flexDirection, ...common],
  "flex-wrap": [...flexWrap, ...common],
  flex: [...commonFlex, "none", ...numeric],
  font: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "bold",
    "bolder",
    "caption",
    "icon",
    "italic",
    "large",
    "larger",
    "lighter",
    "medium",
    "menu",
    "message-box",
    "normal",
    "oblique",
    "small",
    "small-caps",
    "small-caption",
    "smaller",
    "status-bar",
    "x-large",
    "x-small",
    "xx-large",
    "xx-small",
    ...common,
  ],
  fill: ["none", ...cssColorNames],
  "flex-grow": common,
  "flex-shrink": common,
  "font-display": ["auto", "block", "fallback", "optional", "swap", ...common],
  filter,
  "flex-basis": [...commonFlex, ...common],
  "flex-flow": [...flexDirection, ...flexWrap, ...common],
  "font-variant": ["normal", "small-caps", ...common],
  "font-feature-settings": [
    '"aalt"',
    '"abvf"',
    '"abvm"',
    '"abvs"',
    '"afrc"',
    '"akhn"',
    '"blwf"',
    '"blwm"',
    '"blws"',
    '"calt"',
    '"case"',
    '"ccmp"',
    '"cfar"',
    '"cjct"',
    '"clig"',
    '"cpct"',
    '"cpsp"',
    '"cswh"',
    '"curs"',
    '"c2pc"',
    '"c2sc"',
    '"dist"',
    '"dlig"',
    '"dnom"',
    '"dtls"',
    '"expt"',
    '"falt"',
    '"fin2"',
    '"fin3"',
    '"fina"',
    '"flac"',
    '"frac"',
    '"fwid"',
    '"half"',
    '"haln"',
    '"halt"',
    '"hist"',
    '"hkna"',
    '"hlig"',
    '"hngl"',
    '"hojo"',
    '"hwid"',
    '"init"',
    '"isol"',
    '"ital"',
    '"jalt"',
    '"jp78"',
    '"jp83"',
    '"jp90"',
    '"jp04"',
    '"kern"',
    '"lfbd"',
    '"liga"',
    '"ljmo"',
    '"lnum"',
    '"locl"',
    '"ltra"',
    '"ltrm"',
    '"mark"',
    '"med2"',
    '"medi"',
    '"mgrk"',
    '"mkmk"',
    '"nalt"',
    '"nlck"',
    '"nukt"',
    '"numr"',
    '"onum"',
    '"opbd"',
    '"ordn"',
    '"ornm"',
    '"palt"',
    '"pcap"',
    '"pkna"',
    '"pnum"',
    '"pref"',
    '"pres"',
    '"pstf"',
    '"psts"',
    '"pwid"',
    '"qwid"',
    '"rand"',
    '"rclt"',
    '"rlig"',
    '"rkrf"',
    '"rphf"',
    '"rtbd"',
    '"rtla"',
    '"rtlm"',
    '"ruby"',
    '"salt"',
    '"sinf"',
    '"size"',
    '"smcp"',
    '"smpl"',
    '"ssty"',
    '"stch"',
    '"subs"',
    '"sups"',
    '"swsh"',
    '"titl"',
    '"tjmo"',
    '"tnam"',
    '"tnum"',
    '"trad"',
    '"twid"',
    '"unic"',
    '"valt"',
    '"vatu"',
    '"vert"',
    '"vhal"',
    '"vjmo"',
    '"vkna"',
    '"vkrn"',
    '"vpal"',
    '"vrt2"',
    '"zero"',
    "normal",
    "off",
    "on",
    ...common,
  ],
  "forced-color-adjust": ["auto", "none", "preserve-parent-color", ...common],
  "font-variation-settings": common,
  "fill-opacity": numeric,
  "font-variant-ligatures": [
    "additional-ligatures",
    "common-ligatures",
    "contextual",
    "discretionary-ligatures",
    "historical-ligatures",
    "no-additional-ligatures",
    "no-common-ligatures",
    "no-contextual",
    "no-discretionary-ligatures",
    "no-historical-ligatures",
    "none",
    "normal",
    ...common,
  ],
  "font-variant-numeric": [
    "diagonal-fractions",
    "lining-nums",
    "normal",
    "oldstyle-nums",
    "ordinal",
    "proportional-nums",
    "slashed-zero",
    "stacked-fractions",
    "tabular-nums",
    ...common,
  ],
  "fill-rule": commonRule,
  fallback: common,
  "field-sizing": ["content", "fixed", ...common],
  "flood-color": cssColorNames,
  "flood-opacity": numeric,
  "font-kerning": ["auto", "none", "normal", ...common],
  "font-language-override": ["normal", ...common],
  "font-optical-sizing": commonAutoNone,
  "font-palette": common,
  "font-size-adjust": ["none", ...numeric],
  "font-synthesis": ["none", "style", "weight", ...common],
  "font-synthesis-position": commonAutoNone,
  "font-synthesis-small-caps": commonAutoNone,
  "font-synthesis-style": commonAutoNone,
  "font-synthesis-weight": commonAutoNone,
  "font-variant-alternates": [
    "annotation()",
    "character-variant()",
    "historical-forms",
    "normal",
    "ornaments()",
    "styleset()",
    "stylistic()",
    "swash()",
    ...common,
  ],
  "font-variant-caps": [
    "all-petite-caps",
    "all-small-caps",
    "normal",
    "petite-caps",
    "small-caps",
    "titling-caps",
    "unicase",
    ...common,
  ],
  "font-variant-east-asian": [
    "full-width",
    "jis04",
    "jis78",
    "jis83",
    "jis90",
    "normal",
    "proportional-width",
    "ruby",
    "simplified",
    "traditional",
    ...common,
  ],
  "font-variant-emoji": ["normal", "text", "emoji", "unicode", ...common],
  "font-variant-position": ["normal", "sub", "super", ...common],
  gap: numeric,
  "grid-template-columns": gridTemplate,
  "grid-column": commonGrid,
  "grid-template-rows": gridTemplate,
  "grid-area": commonGrid,
  "grid-row": commonGrid,
  "grid-auto-flow": ["row", "column", "dense", ...common],
  "grid-template-areas": ["none", ...common],
  "grid-auto-rows": gridAuto,
  "grid-column-start": commonGrid,
  "grid-row-start": commonGrid,
  "grid-auto-columns": gridAuto,
  "grid-column-end": commonGrid,
  "grid-row-end": commonGrid,
  "glyph-orientation-horizontal": numeric,
  "glyph-orientation-vertical": autoNumeric,
  grid: numeric,
  "grid-template": gridTemplate,
  height: heightWidth,
  hyphens,
  "hanging-punctuation": common,
  "hyphenate-character": common,
  "hyphenate-limit-chars": numeric,
  inset: numeric,
  "inset-inline-start": numeric,
  isolation: ["auto", "isolate", ...common],
  "inline-size": autoNumeric,
  "inset-block-start": common,
  "inset-inline-end": common,
  "image-rendering": [
    "auto",
    "crisp-edges",
    "-moz-crisp-edges",
    "optimizeQuality",
    "optimizeSpeed",
    "pixelated",
    ...common,
  ],
  "inset-block": common,
  "inset-block-end": common,
  "inset-inline": common,
  "image-orientation": ["flip", "from-image", ...numeric],
  "image-resolution": numeric,
  inherits: ["true", "false", ...common],
  "initial-letter": common,
  "initial-letter-align": common,
  "initial-value": common,
  "interpolate-size": ["numeric-only", "allow-keywords", ...common],
  "justify-content": [
    "center",
    "start",
    "end",
    "left",
    "right",
    "safe",
    "unsafe",
    "stretch",
    "space-evenly",
    "flex-end",
    "flex-start",
    "space-around",
    "space-between",
    "baseline",
    "first baseline",
    "last baseline",
    ...common,
  ],
  "justify-items": [...commonJustify, "safe", "unsafe", "legacy", ...common],
  "justify-self": [...commonJustify, "save", "unsave", ...common],
  kerning: autoNumeric,
  left: autoNumeric,
  "line-height": normalNumeric,
  "list-style": [...listStyle, ...listStylePosition, "url()", ...common],
  "letter-spacing": normalNumeric,
  "list-style-type": listStyle,
  "list-style-position": [...listStylePosition, ...common],
  "line-break": ["auto", "loose", "normal", "strict", "anywhere", ...common],
  "list-style-image": noneBackgroundFunctions,
  "lighting-color": cssColorNames,
  "line-clamp": numeric,
  "line-gap-override": numeric,
  "line-height-step": numeric,
  margin: autoNumeric,
  "margin-top": autoNumeric,
  "margin-bottom": autoNumeric,
  "margin-left": autoNumeric,
  "margin-right": autoNumeric,
  "max-width": maxSize,
  "min-height": heightWidth,
  "min-width": heightWidth,
  "max-height": maxSize,
  "margin-inline-start": autoNumeric,
  "mask-image": noneBackgroundFunctions,
  "margin-inline-end": autoNumeric,
  mask: common,
  "margin-block": numeric,
  "margin-block-end": autoNumeric,
  "margin-inline": numeric,
  "mask-position": ["bottom", "center", "left", "right", "top", ...numeric],
  "mask-size": ["contain", "cover", ...autoNumeric],
  "mask-composite": common,
  "mask-repeat": ["no-repeat", "repeat", "repeat-x", "repeat-y", "round", "space", ...common],
  "mix-blend-mode": [
    "normal",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "color-burn",
    "hard-light",
    "soft-light",
    "difference",
    "exclusion",
    "hue",
    "saturation",
    "color",
    "luminosity",
    ...common,
  ],
  "margin-block-start": autoNumeric,
  "max-block-size": autoNumeric,
  "max-inline-size": autoNumeric,
  "min-block-size": autoNumeric,
  "min-inline-size": autoNumeric,
  "mask-mode": ["alpha", "auto", "luminance", ...backgroundFunctions],
  "margin-trim": ["none", "in-flow", "all", ...common],
  marker,
  "marker-end": marker,
  "marker-mid": marker,
  "marker-start": marker,
  marks: common,
  "mask-border": common,
  "mask-border-mode": ["luminance", "alpha", ...common],
  "mask-border-outset": common,
  "mask-border-repeat": common,
  "mask-border-slice": common,
  "mask-border-source": common,
  "mask-border-width": numeric,
  "mask-clip": common,
  "mask-origin": ["fill-box", "margin-box", "stroke-box", "view-box", ...common],
  "mask-type": ["alpha", "luminance", ...common],
  "math-depth": numeric,
  "math-shift": ["compact", "normal", ...common],
  "math-style": ["compact", "normal", ...common],
  "max-lines": numeric,
  motion,
  "motion-offset": numeric,
  "motion-path": motion,
  "motion-rotation": ["reverse", ...autoNumeric],
  "nav-down": nav,
  "nav-index": ["auto", ...common],
  "nav-left": nav,
  "nav-right": nav,
  "nav-up": nav,
  navigation: commonAutoNone,
  negative: backgroundFunctions,
  opacity: numeric,
  overflow: ["-moz-hidden-unscrollable", ...overflow],
  outline: ["auto", "invert", ...borderOptions],
  "overflow-y": overflow,
  "overflow-x": overflow,
  "object-fit": ["contain", "cover", "fill", "none", "scale-down", ...common],
  "outline-offset": numeric,
  order: numeric,
  "overflow-wrap": ["break-word", "normal", "anywhere", ...common],
  "outline-width": borderWidth,
  "outline-color": cssColorNames,
  "outline-style": borderStyle,
  "object-position": position,
  "overflow-anchor": commonAutoNone,
  orphans: numeric,
  "overscroll-behavior-inline": commonAutoNoneClip,
  "object-view-box": common,
  offset: numeric,
  "offset-anchor": numeric,
  "offset-block-end": autoNumeric,
  "offset-block-start": autoNumeric,
  "offset-distance": numeric,
  "offset-inline-end": autoNumeric,
  "offset-inline-start": autoNumeric,
  "offset-path": common,
  "offset-position": numeric,
  "offset-rotate": numeric,
  "overflow-block": overflowClip,
  "overflow-clip-margin": numeric,
  "overflow-inline": overflowClip,
  overlay: commonAutoNone,
  "override-colors": common,
  "overscroll-behavior": common,
  "overscroll-behavior-block": commonAutoNoneClip,
  "overscroll-behavior-x": commonAutoNoneClip,
  "overscroll-behavior-y": commonAutoNoneClip,
  padding: numeric,
  position: [
    "absolute",
    "fixed",
    "-ms-page",
    "relative",
    "static",
    "sticky",
    "-webkit-sticky",
    ...common,
  ],
  "padding-left": numeric,
  "padding-bottom": numeric,
  "padding-right": numeric,
  "padding-top": numeric,
  "pointer-events": [
    "all",
    "fill",
    "none",
    "painted",
    "stroke",
    "visible",
    "visibleFill",
    "visiblePainted",
    "visibleStroke",
    ...common,
  ],
  "padding-inline-start": numeric,
  "padding-block": numeric,
  "padding-inline": numeric,
  "padding-inline-end": numeric,
  "place-content": common,
  "place-items": common,
  "padding-block-end": numeric,
  "padding-block-start": numeric,
  perspective: counter,
  "perspective-origin": ["calc()", ...position], // numeric
  "place-self": common,
  "print-color-adjust": ["economy", "exact", ...common],
  pad: backgroundFunctions,
  page: common,
  "page-orientation": common,
  "paint-order": ["fill", "markers", "normal", "stroke", ...numeric],
  "position-anchor": common,
  "position-area": numeric,
  "position-try": common,
  "position-try-fallbacks": common,
  "position-try-order": numeric,
  "position-visibility": numeric,
  prefix: backgroundFunctions,
  quotes: counter,
  r: numeric,
  right: autoNumeric,
  resize: ["both", "horizontal", "none", "vertical", ...common],
  "row-gap": numeric,
  rotate: numeric,
  range: ["infinite", ...autoNumeric],
  "ruby-align": [
    "auto",
    "center",
    "distribute-letter",
    "distribute-space",
    "left",
    "line-edge",
    "right",
    "start",
    "space-between",
    "space-around",
    ...common,
  ],
  "ruby-merge": ["separate", "collapse", "auto", ...common],
  "ruby-overhang": ["auto", "end", "none", "start", ...common],
  "ruby-position": ["after", "before", "inline", "right", ...common],
  "ruby-span": ["attr(x)", "none", ...common],
  rx: numeric,
  ry: numeric,
  src: ["url()", "format()", "local()", ...common],
  "stroke-width": numeric,
  "scrollbar-width": ["thin", ...commonAutoNone],
  stroke: ["url()", "none", ...cssColorNames],
  "stroke-dashoffset": numeric,
  "stroke-dasharray": numeric,
  "scroll-behavior": ["auto", "smooth", ...common],
  "scroll-snap-type": ["none", "mandatory", "proximity"],
  "scrollbar-color": common,
  "scroll-snap-align": common,
  "scrollbar-gutter": common,
  "stroke-linecap": ["butt", "round", "square", ...common],
  "scroll-padding": numeric,
  size: numeric,
  "stroke-miterlimit": numeric,
  "stroke-opacity": numeric,
  scale: numeric,
  "scroll-snap-stop": ["normal", "always", ...common],
  "stop-opacity": numeric,
  "scroll-padding-top": numeric,
  "stroke-linejoin": ["bevel", "miter", "round", ...common],
  syntax: common,
  "scroll-initial-target": ["none", "nearest", ...common],
  "scroll-margin": numeric,
  "scroll-margin-block": numeric,
  "scroll-margin-block-end": numeric,
  "scroll-margin-block-start": numeric,
  "scroll-margin-bottom": numeric,
  "scroll-margin-inline": numeric,
  "scroll-margin-inline-end": numeric,
  "scroll-margin-inline-start": numeric,
  "scroll-margin-left": numeric,
  "scroll-margin-right": numeric,
  "scroll-margin-top": numeric,
  "scroll-padding-block": numeric,
  "scroll-padding-block-end": numeric,
  "scroll-padding-block-start": numeric,
  "scroll-padding-bottom": numeric,
  "scroll-padding-inline": numeric,
  "scroll-padding-inline-end": numeric,
  "scroll-padding-inline-start": numeric,
  "scroll-padding-left": numeric,
  "scroll-padding-right": numeric,
  "scroll-timeline": common,
  "scroll-timeline-axis": common,
  "scroll-timeline-name": common,
  "scrollbar-3dlight-color": cssColorNames,
  "scrollbar-arrow-color": cssColorNames,
  "scrollbar-base-color": cssColorNames,
  "scrollbar-darkshadow-color": cssColorNames,
  "scrollbar-face-color": cssColorNames,
  "scrollbar-highlight-color": cssColorNames,
  "scrollbar-shadow-color": cssColorNames,
  "scrollbar-track-color": cssColorNames,
  "shape-image-threshold": numeric,
  "shape-margin": numeric,
  "shape-outside": [...paddingCommonBackground, ...backgroundFunctions],
  "shape-rendering": ["auto", "crispEdges", "geometricPrecision", "optimizeSpeed", ...common],
  "size-adjust": numeric,
  "speak-as": common,
  "stop-color": cssColorNames,
  suffix: backgroundFunctions,
  symbols: backgroundFunctions,
  system: [
    "additive",
    "alphabetic",
    "cyclic",
    "extends",
    "fixed",
    "numeric",
    "symbolic",
    ...common,
  ],
  top: numeric,
  "text-align": ["center", "end", "justify", "left", "right", "start", ...common],
  "text-decoration": borderOptions,
  transform,
  transition: transitionTiming,
  "text-transform": ["capitalize", "lowercase", "none", "uppercase", ...common],
  "text-overflow": ["clip", "ellipsis", ...common],
  "transform-origin": ["calc()", ...position], // numeric
  "text-shadow": ["none", ...cssColorNames],
  "touch-action": [
    "auto",
    "cross-slide-x",
    "cross-slide-y",
    "double-tap-zoom",
    "manipulation",
    "none",
    "pan-x",
    "pan-y",
    "pinch-zoom",
    ...common,
  ],
  "transition-duration": numeric,
  "transition-property": ["all", "none", ...common],
  "transition-timing-function": transitionTiming,
  "text-indent": numeric,
  "text-rendering": [
    "auto",
    "geometricPrecision",
    "optimizeLegibility",
    "optimizeSpeed",
    ...common,
  ],
  "transition-delay": numeric,
  "text-size-adjust": numeric,
  "text-decoration-line": ["line-through", "none", "overline", "underline", ...common],
  "table-layout": ["auto", "fixed", ...common],
  "text-decoration-color": cssColorNames,
  "text-wrap": common,
  "transform-style": ["flat", "preserve-3d", ...common],
  "text-decoration-thickness": common,
  "text-underline-offset": numeric,
  "tab-size": numeric,
  "text-decoration-style": ["dashed", "dotted", "double", "none", "solid", "wavy", ...common],
  translate: common,
  "text-align-last": ["auto", "center", "justify", "left", "right", ...common],
  "text-decoration-skip-ink": ["all", ...commonAutoNone],
  "text-wrap-mode": ["nowrap", "wrap", ...common],
  "transform-box": ["content-box", "border-box", "fill-box", "stroke-box", "view-box", ...common],
  "text-anchor": ["end", "middle", "start", ...common],
  "text-box": common,
  "text-box-edge": common,
  "text-box-trim": ["none", "trim-start", "trim-end", "trim-both", ...common],
  "text-combine-upright": common,
  "text-decoration-skip": common,
  "text-emphasis": common,
  "text-emphasis-color": cssColorNames,
  "text-emphasis-position": common,
  "text-emphasis-style": common,
  "text-justify": [
    "auto",
    "distribute",
    "distribute-all-lines",
    "inter-cluster",
    "inter-ideograph",
    "inter-word",
    "kashida",
    "newspaper",
    ...common,
  ],
  "text-orientation": ["sideways", "sideways-right", "upright", ...common],
  "text-spacing-trim": ["space-all", "normal", "space-first", "trim-start", ...common],
  "text-underline-position": ["above", "auto", "below", ...common],
  "text-wrap-style": ["auto", "balance", "stable", "pretty", ...common],
  "timeline-scope": common,
  "transition-behavior": common,
  types: common,
  "user-select": ["all", "auto", "contain", "none", "text", ...common],
  "unicode-range": [
    "U+26",
    "U+20-24F, U+2B0-2FF, U+370-4FF, U+1E00-1EFF, U+2000-20CF, U+2100-23FF, U+2500-26FF, U+E000-F8FF, U+FB00-FB4F",
    "U+20-17F, U+2B0-2FF, U+2000-206F, U+20A0-20CF, U+2100-21FF, U+2600-26FF",
    "U+20-2FF, U+370-4FF, U+1E00-20CF, U+2100-23FF, U+2500-26FF, U+FB00-FB4F, U+FFF0-FFFD",
    "U+20-4FF, U+530-58F, U+10D0-10FF, U+1E00-23FF, U+2440-245F, U+2500-26FF, U+FB00-FB4F, U+FE20-FE2F, U+FFF0-FFFD",
    "U+00-7F",
    "U+80-FF",
    "U+100-17F",
    "U+180-24F",
    "U+1E00-1EFF",
    "U+250-2AF",
    "U+370-3FF",
    "U+1F00-1FFF",
    "U+400-4FF",
    "U+500-52F",
    "U+00-52F, U+1E00-1FFF, U+2200-22FF",
    "U+530-58F",
    "U+590-5FF",
    "U+600-6FF",
    "U+750-77F",
    "U+8A0-8FF",
    "U+700-74F",
    "U+900-97F",
    "U+980-9FF",
    "U+A00-A7F",
    "U+A80-AFF",
    "U+B00-B7F",
    "U+B80-BFF",
    "U+C00-C7F",
    "U+C80-CFF",
    "U+D00-D7F",
    "U+D80-DFF",
    "U+118A0-118FF",
    "U+E00-E7F",
    "U+1A20-1AAF",
    "U+AA80-AADF",
    "U+E80-EFF",
    "U+F00-FFF",
    "U+1000-109F",
    "U+10A0-10FF",
    "U+1200-137F",
    "U+1380-139F",
    "U+2D80-2DDF",
    "U+AB00-AB2F",
    "U+1780-17FF",
    "U+1800-18AF",
    "U+1B80-1BBF",
    "U+1CC0-1CCF",
    "U+4E00-9FD5",
    "U+3400-4DB5",
    "U+2F00-2FDF",
    "U+2E80-2EFF",
    "U+1100-11FF",
    "U+AC00-D7AF",
    "U+3040-309F",
    "U+30A0-30FF",
    "U+A5, U+4E00-9FFF, U+30??, U+FF00-FF9F",
    "U+A4D0-A4FF",
    "U+A000-A48F",
    "U+A490-A4CF",
    "U+2000-206F",
    "U+3000-303F",
    "U+2070-209F",
    "U+20A0-20CF",
    "U+2100-214F",
    "U+2150-218F",
    "U+2190-21FF",
    "U+2200-22FF",
    "U+2300-23FF",
    "U+E000-F8FF",
    "U+FB00-FB4F",
    "U+FB50-FDFF",
    "U+1F600-1F64F",
    "U+2600-26FF",
    "U+1F300-1F5FF",
    "U+1F900-1F9FF",
    "U+1F680-1F6FF",
    ...common,
  ],
  "unicode-bidi": [
    "bidi-override",
    "embed",
    "isolate",
    "isolate-override",
    "normal",
    "plaintext",
    ...common,
  ],
  "vertical-align": [
    "auto",
    "baseline",
    "bottom",
    "middle",
    "sub",
    "super",
    "text-bottom",
    "text-top",
    "top",
    "-webkit-baseline-middle",
    ...numeric,
  ],
  visibility: ["collapse", "hidden", "visible", ...numeric],
  "vector-effect": [
    "none",
    "non-scaling-stroke",
    "non-scaling-size",
    "non-rotation",
    "fixed-position",
    ...common,
  ],
  "view-timeline": common,
  "view-timeline-axis": common,
  "view-timeline-inset": common,
  "view-timeline-name": common,
  "view-transition-class": common,
  "view-transition-name": common,
  width: heightWidth,
  "white-space": common,
  "word-break": ["break-all", "keep-all", "normal", ...common],
  "word-wrap": ["break-word", "normal", ...common],
  "will-change": ["auto", "contents", "scroll-position", ...common],
  "word-spacing": ["normal", ...numeric],
  "writing-mode": [
    "horizontal-tb",
    "sideways-lr",
    "sideways-rl",
    "vertical-lr",
    "vertical-rl",
    ...common,
  ],
  widows: common,
  "white-space-collapse": [
    "collapse",
    "preserve",
    "preserve-breaks",
    "preserve-spaces",
    "break-spaces",
    ...common,
  ],
  x: numeric,
  y: numeric,
  "z-index": autoNumeric,
  zoom,
  "-moz-animation": animation,
  "-moz-animation-delay": numeric,
  "-moz-animation-direction": [...animationDirection, ...common],
  "-moz-animation-duration": numeric,
  "-moz-animation-iteration-count": animationIterationCount,
  "-moz-animation-name": ["none", ...common],
  "-moz-animation-play-state": ["paused", "running", ...common],
  "-moz-animation-timing-function": animation,
  "-moz-backface-visibility": [...visibility, ...common],
  "-moz-background-clip": ["padding", ...paddingCommonBackground, ...common],
  "-moz-background-inline-policy": ["bounding-box", "continuous", "each-box", ...common],
  "-moz-background-origin": [...paddingCommonBackground, ...common],
  "-moz-border-image": ["auto", "fill", "none", ...commonImage, "url()", ...common],
  "-moz-box-align": ["baseline", "center", "end", "start", "stretch", ...common],
  "-moz-box-direction": ["normal", "reverse", ...common],
  "-moz-box-flex": common,
  "-moz-box-flexgroup": common,
  "-moz-box-ordinal-group": common,
  "-moz-box-orient": ["block-axis", "horizontal", "inline-axis", "vertical", ...common],
  "-moz-box-pack": ["center", "end", "justify", "start", ...common],
  "-moz-box-sizing": ["border-box", "content-box", "padding-box", ...common],
  "-moz-column-count": autoNumeric,
  "-moz-column-gap": normalNumeric,
  "-moz-column-rule": borderOptions,
  "-moz-column-rule-color": cssColorNames,
  "-moz-column-rule-style": borderStyle,
  "-moz-column-rule-width": borderWidth,
  "-moz-column-width": autoNumeric,
  "-moz-columns": autoNumeric,
  "-moz-font-feature-settings": [
    '"c2cs"',
    '"dlig"',
    '"kern"',
    '"liga"',
    '"lnum"',
    '"onum"',
    '"smcp"',
    '"swsh"',
    '"tnum"',
    "normal",
    "off",
    "on",
    ...common,
  ],
  "-moz-hyphens": hyphens,
  "-moz-perspective": counter,
  "-moz-perspective-origin": ["calc()", ...position], // numeric
  "-moz-text-align-last": ["auto", "center", "justify", "left", "right", ...common],
  "-moz-text-decoration-color": cssColorNames,
  "-moz-text-decoration-line": ["line-through", "none", "overline", "underline", ...common],
  "-moz-text-decoration-style": ["dashed", "dotted", "double", "none", "solid", "wavy", ...common],
  "-moz-text-size-adjust": ["none", ...autoNumeric],
  "-moz-transform": transform,
  "-moz-transform-origin": ["calc()", ...position], // numeric
  "-moz-transition": transitionTiming,
  "-moz-transition-delay": numeric,
  "-moz-transition-duration": numeric,
  "-moz-transition-property": ["all", "none", ...common],
  "-moz-transition-timing-function": transitionTiming,
  "-moz-user-select": [
    "all",
    "element",
    "elements",
    "-moz-all",
    "-moz-none",
    "none",
    "text",
    "toggle",
    ...common,
  ],
  "-ms-behavior": common,
  "-ms-flex": ["auto", "none", ...numeric],
  "-ms-flex-align": ["baseline", "center", "end", "start", "stretch", ...common],
  "-ms-flex-direction": [...flexDirection, ...common],
  "-ms-flex-flow": ["column", "column-reverse", "nowrap", "row", "wrap", "wrap-reverse", ...common],
  "-ms-flex-item-align": ["auto", "baseline", "center", "end", "start", "stretch", ...common],
  "-ms-flex-line-pack": ["center", "distribute", "end", "justify", "start", "stretch", ...common],
  "-ms-flex-order": common,
  "-ms-flex-pack": ["center", "distribute", "end", "justify", "start", ...common],
  "-ms-flex-wrap": [...flexWrap, ...common],
  "-ms-grid-column": ["auto", "end", "start", ...common],
  "-ms-grid-column-align": ["center", "end", "start", "stretch", ...common],
  "-ms-grid-column-span": common,
  "-ms-grid-layer": common,
  "-ms-grid-row": ["auto", "end", "start", ...common],
  "-ms-grid-row-align": ["center", "end", "start", "stretch", ...common],
  "-ms-grid-row-span": common,
  "-ms-hyphens": hyphens,
  "-ms-ime-mode": ["active", "auto", "disabled", "inactive", "normal", ...common],
  "-ms-interpolation-mode": ["bicubic", "nearest-neighbor", ...common],
  "-ms-layout-grid": ["char", "line", "mode", "type", ...common],
  "-ms-layout-grid-char": ["none", ...autoNumeric],
  "-ms-layout-grid-line": ["none", ...autoNumeric],
  "-ms-layout-grid-mode": ["both", "char", "line", "none", ...common],
  "-ms-layout-grid-type": ["fixed", "loose", "strict", ...common],
  "-ms-line-break": ["auto", "keep-all", "newspaper", "normal", "strict", ...common],
  "-ms-perspective": counter,
  "-ms-perspective-origin": ["calc()", ...position], // numeric
  "-ms-perspective-origin-x": ["calc()", ...position], // numeric
  "-ms-perspective-origin-y": ["calc()", ...position], // numeric
  "-ms-progress-appearance": ["bar", "ring", ...common],
  "-ms-text-align-last": ["auto", "center", "justify", "left", "right", ...common],
  "-ms-text-combine-horizontal": ["all", "digits", "none", ...common],
  "-ms-text-justify": [
    "auto",
    "distribute",
    "inter-cluster",
    "inter-ideograph",
    "inter-word",
    "kashida",
    ...common,
  ],
  "-ms-text-kashida-space": numeric,
  "-ms-text-overflow": ["clip", "ellipsis", ...common],
  "-ms-text-size-adjust": ["none", ...autoNumeric],
  "-ms-text-underline-position": ["alphabetic", "auto", "over", "under", ...common],
  "-ms-touch-action": [
    "auto",
    "double-tap-zoom",
    "manipulation",
    "none",
    "pan-x",
    "pan-y",
    "pinch-zoom",
    ...common,
  ],
  "-ms-transform": [
    "matrix()",
    "matrix3d()",
    "none",
    "rotate()",
    "rotate3d()",
    "rotateX('angle')",
    "rotateY('angle')",
    "rotateZ('angle')",
    "scale()",
    "scale3d()",
    "scaleX()",
    "scaleY()",
    "scaleZ()",
    "skew()",
    "skewX()",
    "skewY()",
    "translate()",
    "translate3d()",
    "translateX()",
    "translateY()",
    "translateZ()",
    ...common,
  ],
  "-ms-transform-origin": ["calc()", ...position], // numeric
  "-ms-transform-origin-x": numeric,
  "-ms-transform-origin-y": numeric,
  "-ms-transform-origin-z": numeric,
  "-ms-word-break": ["break-all", "keep-all", "normal", ...common],
  "-ms-word-wrap": ["break-word", "normal", ...common],
  "-ms-writing-mode": [
    "bt-lr",
    "bt-rl",
    "lr-bt",
    "lr-tb",
    "rl-bt",
    "rl-tb",
    "tb-lr",
    "tb-rl",
    ...common,
  ],
  "-ms-zoom": zoom,
  "-ms-zoom-animation": ["default", "none", ...common],
  "-o-animation": animation,
  "-o-animation-delay": numeric,
  "-o-animation-direction": [...animationDirection, ...common],
  "-o-animation-duration": numeric,
  "-o-animation-fill-mode": ["forwards", ...animationFillMode],
  "-o-animation-iteration-count": animationIterationCount,
  "-o-animation-name": ["none", ...common],
  "-o-animation-play-state": ["paused", "running", ...common],
  "-o-animation-timing-function": animation,
  "-o-border-image": ["auto", "fill", "none", ...commonImage, "url()", ...common],
  "-o-object-fit": ["contain", "cover", "fill", "none", "scale-down", ...common],
  "-o-object-position": position,
  "-o-tab-size": numeric,
  "-o-table-baseline": common,
  "-o-text-overflow": ["clip", "ellipsis", ...common],
  "-o-transform": [
    "matrix()",
    "matrix3d()",
    "none",
    "rotate()",
    "rotate3d()",
    "rotateX('angle')",
    "rotateY('angle')",
    "rotateZ('angle')",
    "scale()",
    "scale3d()",
    "scaleX()",
    "scaleY()",
    "scaleZ()",
    "skew()",
    "skewX()",
    "skewY()",
    "translate()",
    "translate3d()",
    "translateX()",
    "translateY()",
    "translateZ()",
    ...common,
  ],
  "-o-transform-origin": ["calc()", ...position], // numeric
  "-o-transition": transitionTiming,
  "-o-transition-delay": numeric,
  "-o-transition-duration": numeric,
  "-o-transition-property": ["all", "none", ...common],
  "-o-transition-timing-function": transitionTiming,
  "-webkit-animation": animation,
  "-webkit-animation-delay": numeric,
  "-webkit-animation-direction": [...animationDirection, ...common],
  "-webkit-animation-duration": numeric,
  "-webkit-animation-fill-mode": ["forwards", ...animationFillMode],
  "-webkit-animation-iteration-count": animationIterationCount,
  "-webkit-animation-name": ["none", ...common],
  "-webkit-animation-play-state": ["paused", "running", ...common],
  "-webkit-animation-timing-function": animation,
  "-webkit-backdrop-filter": [
    "none",
    "blur()",
    "brightness()",
    "contrast()",
    "drop-shadow()",
    "grayscale()",
    "hue-rotate()",
    "invert()",
    "opacity()",
    "saturate()",
    "sepia()",
    "url()",
    ...common,
  ],
  "-webkit-backface-visibility": [...visibility, ...common],
  "-webkit-background-clip": [...paddingCommonBackground, ...common],
  "-webkit-background-composite": ["border", "padding", ...common],
  "-webkit-background-origin": [...paddingCommonBackground, ...common],
  "-webkit-border-image": ["auto", "fill", "none", ...commonImage, "url()", ...common],
  "-webkit-box-align": ["baseline", "center", "end", "start", "stretch", ...common],
  "-webkit-box-direction": ["normal", "reverse", ...common],
  "-webkit-box-flex": common,
  "-webkit-box-flex-group": common,
  "-webkit-box-ordinal-group": common,
  "-webkit-box-orient": ["block-axis", "horizontal", "inline-axis", "vertical", ...common],
  "-webkit-box-pack": ["center", "end", "justify", "start", ...common],
  "-webkit-box-sizing": [...commonBackground, ...common],
  "-webkit-break-after": webkitCommonBreak,
  "-webkit-break-before": webkitCommonBreak,
  "-webkit-break-inside": webkitCommonBreakInside,
  "-webkit-column-break-after": webkitCommonBreak,
  "-webkit-column-break-before": webkitCommonBreak,
  "-webkit-column-break-inside": webkitCommonBreakInside,
  "-webkit-column-count": autoNumeric,
  "-webkit-column-gap": normalNumeric,
  "-webkit-column-rule": borderOptions,
  "-webkit-column-rule-color": cssColorNames,
  "-webkit-column-rule-style": borderStyle,
  "-webkit-column-rule-width": borderWidth,
  "-webkit-column-span": ["all", "none", ...common],
  "-webkit-column-width": autoNumeric,
  "-webkit-columns": autoNumeric,
  "-webkit-filter": filter,
  "-webkit-flow-from": ["none", ...common],
  "-webkit-flow-into": ["none", ...common],
  "-webkit-font-feature-settings": [
    '"c2cs"',
    '"dlig"',
    '"kern"',
    '"liga"',
    '"lnum"',
    '"onum"',
    '"smcp"',
    '"swsh"',
    '"tnum"',
    "normal",
    "off",
    "on",
    ...common,
  ],
  "-webkit-hyphens": hyphens,
  "-webkit-line-break": ["after-white-space", "normal", ...common],
  "-webkit-line-clamp": common,
  "-webkit-margin-bottom-collapse": marginCollapse,
  "-webkit-margin-collapse": marginCollapse,
  "-webkit-margin-start": autoNumeric,
  "-webkit-margin-top-collapse": marginCollapse,
  "-webkit-nbsp-mode": ["normal", "space", ...common],
  "-webkit-padding-start": numeric,
  "-webkit-perspective": counter,
  "-webkit-perspective-origin": ["calc()", ...position], // numeric
  "-webkit-region-fragment": ["auto", "break", ...common],
  "-webkit-text-fill-color": cssColorNames,
  "-webkit-text-size-adjust": ["none", ...autoNumeric],
  "-webkit-text-stroke": [...cssColorNames, ...numeric],
  "-webkit-text-stroke-color": cssColorNames,
  "-webkit-text-stroke-width": borderWidth,
  "-webkit-transform": transform,
  "-webkit-transform-origin": ["calc()", ...position], // numeric
  "-webkit-transform-origin-x": numeric,
  "-webkit-transform-origin-y": numeric,
  "-webkit-transform-origin-z": numeric,
  "-webkit-transform-style": ["flat", ...common],
  "-webkit-transition": transitionTiming,
  "-webkit-transition-delay": numeric,
  "-webkit-transition-duration": numeric,
  "-webkit-transition-property": ["all", "none", ...common],
  "-webkit-transition-timing-function": transitionTiming,
  "-webkit-user-drag": ["auto", "element", "none", ...common],

  // @at
  "@media": [],
  "@keyframes": [],
  "@-moz-document": [],
  "@-moz-keyframes": [],
  "@-ms-viewport": [],
  "@-o-keyframes": [],
  "@-o-viewport": [],
  "@-webkit-keyframes": [],
  "@charset": [],
  "@container": [],
  "@counter-style": [],
  "@document": [],
  "@font-face": [],
  "@font-feature-values": [],
  "@font-palette-values": [],
  "@import": [],
  "@layer": [],
  "@namespace": [],
  "@page": [],
  "@position-try": [],
  "@property": [],
  "@scope": [],
  "@starting-style": [],
  "@supports": [],
  "@view-transition": [],
};
