services: 
  vite-client:
    image: vite-client:latest
    environment:
      - NODE_ENV=development
    build:
      dockerfile: ./docker/Dockerfile.vite-client
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/vite-client/
        target: /usr/src/app/
      - type: bind
        source: ./packages/
        target: /usr/src/app/packages/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: ./apps/vite-client/vite.config.ts
        target: /usr/src/app/vite.config.ts
    networks:
      - frontend
    ports:
      - 5173:5173
  remix:
    image: remix:latest
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    build:
      dockerfile: ./docker/Dockerfile.remix
      context: ./
      target: dev
    init: true
    volumes: 
      - type: bind
        source: ./apps/remix/
        target: /usr/src/app/
      - type: bind
        source: ./packages/
        target: /usr/src/app/packages/
      - type: volume
        target: /usr/src/app/node_modules 
    networks: 
      - frontend
    ports: 
      - 3000:3000
      - 3001:3001
networks:
  frontend: