services: 
  vite-client:
    image: vite-client:latest
    build:
      dockerfile: ./docker/Dockerfile.vite-client
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/vite-client
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: ./apps/vite-client/vite.config.ts
        target: /usr/src/app/vite.config.ts
    networks:
      - frontend
    ports:
      - 5173:5173
networks:
  frontend: