services:
  express-backend:
    image: express-backend:latest
    environment:
      - NODE_ENV=development
      - CHOKIDAR_INTERVAL=1000
    build:
      dockerfile: ./docker/Dockerfile.express-backend
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/express-backend/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./packages/shared-types
        target: /usr/src/app/packages/shared-types
      - type: bind
        source: ./packages/test
        target: /usr/src/app/packages/test
      - type: bind
        source: ./packages/test-dependency
        target: /usr/src/app/packages/test-dependency
    networks:
      - backend
    ports:
      - '3002:3002'
  next:
    image: next:latest
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - WATCHPACK_INTERVAL=1000
    build:
      dockerfile: ./docker/Dockerfile.next
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/next/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./packages/test
        target: /usr/src/app/packages/test
      - type: bind
        source: ./packages/test-dependency
        target: /usr/src/app/packages/test-dependency
    networks:
      - frontend
    ports:
      - '3003:3003'
  remix:
    image: remix:latest
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    build:
      dockerfile: ./docker/Dockerfile.remix
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/remix/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./packages/test
        target: /usr/src/app/packages/test
      - type: bind
        source: ./packages/test-dependency
        target: /usr/src/app/packages/test-dependency
    networks:
      - frontend
    ports:
      - '3000:3000'
      - '3001:3001'
  vite-client:
    image: vite-client:latest
    environment:
      - NODE_ENV=development
      - CHOKIDAR_INTERVAL=1000
    build:
      dockerfile: ./docker/Dockerfile.vite-client
      context: ./
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./apps/vite-client/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./packages/test
        target: /usr/src/app/packages/test
      - type: bind
        source: ./packages/test-dependency
        target: /usr/src/app/packages/test-dependency
      - type: bind
        source: ./packages/shared-types
        target: /usr/src/app/packages/shared-types
      - type: bind
        source: ./apps/vite-client/vite.config.ts
        target: /usr/src/app/vite.config.ts
    networks:
      - frontend
    ports:
      - '5173:5173'
networks:
  frontend:
    name: frontend
  backend:
    name: backend
