export const TokenTypes = {
  DEFINITION: "definition",
  VARIABLE: "variable",
  CONST_VARIABLE: "const-variable",
  FUNCTION_NAME: "function-name",
  STRING: "string",
  TYPE_DEFINITION: "type-definition",
  TYPE: "type",
  STRING_TYPE: "string-type",
  WHITESPACE: "whitespace",
  EQUAL: "equal",
  END_OF_LINE: "end-of-line",
  TYPE_COLON: "type-colon",
  TYPE_OR: "type-or",
  TYPE_AND: "type-and",
  IMPORT: "import",
  IMPORT_VARIABLE: "import-variable",
  IMPORT_CURLY_BRACKET: "import-curly-bracket",
  ARRAY_SQUARE_BRACKET: "array-square-bracket",
  OBJECT_CURLY_BRACKET: "object-curly-bracket",
  OBJECT_PROPERTY: "object-property",
  OBJECT_STRING_PROPERTY: "object-string-property",
  OBJECT_STRING_TYPE_PROPERTY: "object-string-type-property",
  OBJECT_COLON: "object-colon",
  PARENTHESIS: "parenthesis",
  ANGLE: "angle",
  AS: "as",
  FROM: "from",
  COMMA: "comma",
  UNKNOWN: "unknown",
  OPERATOR: "operator",
  COMMENT: "comment",
  ARROW: "arrow",
  NUMBER: "number",
  EXTENDS: "extends",
  JSX: "jsx",
  JSX_PROPERTY: "jsx-property",
  TAG_CONTENT: "tag-content",
  FUNCTION_CURLY_BRACKET: "function-curly-bracket",
  RETURN: "return",
  BOOLEAN: "boolean",
  FUNCTION: "function",
  JSX_PROPERTY_EXPRESSION_INTERPOLATION: "jsx-property-expression-interpolation",
  UNDEFINED: "undefined",
  NULL: "null",
  NEW: "new",
  CLASS_NAME: "class-name",
  CLASS: "class",
  CLASS_CURLY_BRACKET: "class-curly-bracket",
  PUBLIC: "public",
  PRIVATE: "private",
  STATIC: "static",
  ABSTRACT: "abstract",
  CLASS_CONSTRUCTOR: "class-constructor",
  NUMERIC_CLASS_VARIABLE: "numeric-class-variable",
  THIS: "this",
  INVOKED_FUNCTION: "invoked-function",
  IF: "if",
  IF_CURLY_BRACKET: "if-curly-bracket",
  TEMPLATE_LITERAL_EXPRESSION_INTERPOLATION: "template-literal-expression-interpolation",
  KEYOF: "keyof",
  TYPEOF: "typeof",
  OBJECT_CURLY_TYPE_BRACKET: "object-curly-type-bracket",
  ARRAY_SQUARE_TYPE_BRACKET: "array-square-type-bracket",
  TYPE_PARENTHESIS: "type-parenthesis",
  TYPE_OPTIONAL_ARGUMENT: "optional-argument",
  AND: "and",
  OR: "or",
  LOWER_THAN: "lower-than",
  HIGHTER_THAN: "higher-than",
  LOWER_THAN_EQUAL: "lower-than-equal",
  HIGHER_THAN_EQUAL: "higher-than-equal",
  TERINARY_QUESTION_MARK: "terinary-question-mark",
  TERINARY_COLON: "terinary-colon",
  ARITHMETIC_OPERATOR: "arithmetic-operator",
  IS_EQUAL: "is-equal",
  IS_UNEQUAL: "is-unequal",
  IS_DEEP_EQUAL: "is-deep-equal",
  IS_DEEP_UNEQUAL: "is-deep-unequal",
} as const;

export type TokenTypeOptions = (typeof TokenTypes)[keyof typeof TokenTypes];

export const definitionKeywords = new Set<string>(["var", "let", "const"]);
export const stringDefinitions = new Set<string>(["'", '"']);
export const valueArithmetics = new Set<string>(["+", "-", "*", "/", "^", "%"]);
export const operators = new Set<string>([".", ":", ",", ";", "=", "!", "?", ...valueArithmetics]);
export const breakpoints = new Set<string>([
  " ",
  "{",
  "}",
  "(",
  ")",
  "`",
  "&",
  "|",
  "\n",
  "<",
  ">",
  "[",
  "]",
  ...operators,
  ...stringDefinitions,
]);

export const acceptableCharactersAfterANumber = new Set<string>([
  "+",
  "-",
  "*",
  "/",
  "%",
  "^",
  "&",
  "|",
  ">",
  "<",
  "=",
  " ",
  ";",
  "}",
  ",",
  "]",
]);

export const classSpecificKeywords = new Set(["public", "private", "static"]);

export const htmlTags = new Set([
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "keygen",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "menu",
  "menuitem",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
]);

export const keywords = new Set<string>([
  "if",
  "else",
  "switch",
  "case",
  "default",
  "for",
  "while",
  "do",
  "break",
  "continue",
  "return",
  "throw",
  "try",
  "catch",
  "finally",
  "class",
  "interface",
  "enum",
  "extends",
  "implements",
  "type",
  "namespace",
  "module",
  "declare",
  "abstract",
  "function",
  "constructor",
  "new",
  "delete",
  "import",
  "export",
  "from",
  "as",
  "static",
  "public",
  "private",
  "protected",
  "readonly",
  "override",
]);

export const types = new Set<string>([
  "any",
  "void",
  "never",
  "unknown",
  "boolean",
  "number",
  "string",
  "object",
  "symbol",
  "bigint",
  "null",
  "undefined",
  "keyof",
  "typeof",
  "infer",
  "is",
  "asserts",
  "async",
  "await",
  "implements",
  "package",
]);
