export const SupportedCommands = {
  HELP: "help",
  DOCKER_COMPOSE_DEV: "docker-compose-dev",
  DOCKERFILE: "dockerfile",
  PACKAGE: "package",
  CONTAINER: "container",
  GENERATE_POSTGRES_TYPES: "generate-postgres-types",
  VITE_ALIASES: "vite-aliases",
  PACKAGE_LOCK: "package-lock",
  CHANGED_FILES: "changed-files",
  GENERATE_GITHUB_ACTION_YAMLS: "generate-github-action-yaml",
  DETECT_CIRCULAR_DEPENDENCIES: "detect-circular-dependencies",
  SETUP_PACKAGE: "setup-package",
  DETECT_UNDEVELOPED_PACKAGES: "detect-undeveloped-packages",
  CREATE_TYPECHECK_GITHUB_ACTION_CONFIG_FILES: "create-typecheck-github-action-config-files",
  CLI: "cli",
  DEPENDENCY_TREES: "dependency-trees",
  DEBUG_EXTENSION: "debug-extension",
} as const;
