import { TokenTypeOptions, TokenTypes } from "./constants";

export const baseColors: Record<TokenTypeOptions, string> = {
  [TokenTypes.STRING]: "#CE723C",
  [TokenTypes.VARIABLE]: "#50B9FE",
  [TokenTypes.CONST_VARIABLE]: "#2B1FA8",
  [TokenTypes.DEFINITION]: "#4A9CB3",
  [TokenTypes.TYPE]: "#44C990",
  [TokenTypes.EXTENDS]: "purple",
  [TokenTypes.JSX]: "darkGreen",
  [TokenTypes.JSX_PROPERTY]: "#50B9FE",
  [TokenTypes.FUNCTION]: "#DCDCAA",
  [TokenTypes.IMPORT]: "purple",
  [TokenTypes.IMPORT_VARIABLE]: "#50B9FE",
  [TokenTypes.COMMENT]: "darkGreen",
  [TokenTypes.AS]: "purple",
  [TokenTypes.FROM]: "purple",
  [TokenTypes.IMPORT_CURLY_BRACKET]: "white",
  [TokenTypes.OBJECT_CURLY_BRACKET]: "white",
  [TokenTypes.OBJECT_PROPERTY]: "#50B9FE",
  [TokenTypes.ARROW]: "#4A9CB3",
  [TokenTypes.NUMBER]: "lightGreen",
  [TokenTypes.ANGLE]: "white",
  [TokenTypes.OBJECT_COLON]: "white",
  [TokenTypes.EQUAL]: "white",
  [TokenTypes.END_OF_LINE]: "white",
  [TokenTypes.WHITESPACE]: "white",
  [TokenTypes.COMMA]: "white",
  [TokenTypes.TYPE_COLON]: "white",
  [TokenTypes.TYPE_OR]: "white",
  [TokenTypes.TYPE_AND]: "white",
  [TokenTypes.OPERATOR]: "white",
  [TokenTypes.ARRAY_SQUARE_BRACKET]: "white",
  [TokenTypes.PARENTHESIS]: "white",
  [TokenTypes.TAG_CONTENT]: "white",
  [TokenTypes.UNKNOWN]: "white",
};
