[tool.poetry]
name = "tts"
version = "0.1.0"
description = ""
authors = ["guypersonalgithub <zeraptos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pyright = "^1.1.383"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
