name: Create Typecheck Github Actions Config Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/create-typecheck-github-actions-config/**
      - typescript/dev-packages/paths/**
      - typescript/packages/utils/**
      - typescript/dev-packages/package-json/**
      - typescript/dev-packages/files/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd dev-packages/create-typecheck-github-actions-config && npm run typecheck
