name: CS Netlify Production Deployment
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.CS_NETLIFY_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.CS_NETLIFY_SITE_ID }}
on:
  push:
    branches:
      - main
    paths:
      - typescript/apps/cs/**
      - typescript/packages/icons/**
      - typescript/packages/mathml/**
      - typescript/packages/math-parser/**
      - typescript/packages/router/**
      - typescript/packages/utils/**
      - typescript/packages/url/**
      - typescript/packages/environment/**
      - typescript/packages/design-patterns/**
      - typescript/packages/randomizer/**
      - typescript/packages/sidebar/**
      - typescript/packages/animation-container/**
      - typescript/packages/is-dev/**
      - typescript/packages/button/**
      - typescript/packages/tooltip/**
      - typescript/packages/edge-intersection/**
      - typescript/packages/auto-complete-input/**
      - typescript/packages/typeahead/**
      - typescript/packages/input/**
      - typescript/packages/loading/**
      - typescript/packages/virtual-list/**
      - typescript/packages/hooks/**
      - typescript/packages/table/**
      - typescript/packages/pagination/**
      - typescript/packages/copy-to-clipboard/**
      - typescript/packages/calculations-table/**
  workflow_dispatch: 
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      - name: Install Netlify CLI
        run: npm i --save-dev netlify-cli
      - name: Create working folder
        run: mkdir full-application
      - name: Remove postinstall
        run: node removePostInstall.js cs
      - name: Copy root package.json
        run: cp -r package.json ./full-application/
      - name: Copy workspace
        run: |
          mkdir -p ./full-application/apps
          cp -r ./apps/cs ./full-application/apps
      - name: Copy dependencies
        run: |
          mkdir -p ./full-application/packages
          cp -r ./packages/icons ./full-application/packages
          cp -r ./packages/mathml ./full-application/packages
          cp -r ./packages/math-parser ./full-application/packages
          cp -r ./packages/router ./full-application/packages
          cp -r ./packages/utils ./full-application/packages
          cp -r ./packages/url ./full-application/packages
          cp -r ./packages/environment ./full-application/packages
          cp -r ./packages/design-patterns ./full-application/packages
          cp -r ./packages/randomizer ./full-application/packages
          cp -r ./packages/sidebar ./full-application/packages
          cp -r ./packages/animation-container ./full-application/packages
          cp -r ./packages/is-dev ./full-application/packages
          cp -r ./packages/button ./full-application/packages
          cp -r ./packages/tooltip ./full-application/packages
          cp -r ./packages/edge-intersection ./full-application/packages
          cp -r ./packages/auto-complete-input ./full-application/packages
          cp -r ./packages/typeahead ./full-application/packages
          cp -r ./packages/input ./full-application/packages
          cp -r ./packages/loading ./full-application/packages
          cp -r ./packages/virtual-list ./full-application/packages
          cp -r ./packages/hooks ./full-application/packages
          cp -r ./packages/table ./full-application/packages
          cp -r ./packages/pagination ./full-application/packages
          cp -r ./packages/copy-to-clipboard ./full-application/packages
          cp -r ./packages/calculations-table ./full-application/packages
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: netlify deploy --prod --dir=./apps/cs/dist
