name: CS Netlify Production Deployment
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.CS_NETLIFY_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.CS_NETLIFY_SITE_ID }}
on:
  push:
    branches:
      - main
    paths:
      - typescript/apps/cs/**
  workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      - name: Install Netlify CLI
        run: npm i --save-dev netlify-cli
      - name: Create working folder
        run: mkdir full-application
      - name: Remove postinstall
        run: node removePostInstall.js cs
      - name: Copy root package.json
        run: cp -r package.json ./full-application/
      - name: Copy workspace
        run: |
          mkdir -p ./full-application/apps
          cp -r ./apps/cs ./full-application/apps
      - name: Copy dependencies
        run: mkdir -p ./full-application/packages
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: netlify deploy --prod --dir=./apps/cs/dist
