name: CS Netlify Production Deployment
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.CS_NETLIFY_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.CS_NETLIFY_SITE_ID }}
on:
  push:
    branches:
      - main
    paths:
      - typescript/apps/cs/**
      - typescript/packages/icons/**
      - typescript/packages/mathml/**
      - typescript/packages/math-parser/**
      - typescript/packages/string-utils/**
      - typescript/packages/regex/**
      - typescript/packages/router/**
      - typescript/packages/utils/**
      - typescript/packages/url/**
      - typescript/packages/environment/**
      - typescript/packages/hooks/**
      - typescript/packages/array-utils/**
      - typescript/packages/object-utils/**
      - typescript/packages/parse-typescript/**
      - typescript/packages/sidebar/**
      - typescript/packages/animation-container/**
      - typescript/packages/is-dev/**
      - typescript/packages/button/**
      - typescript/packages/tooltip/**
      - typescript/packages/randomizer/**
      - typescript/packages/edge-intersection/**
      - typescript/packages/element-utils/**
      - typescript/packages/calculate-relative-position/**
      - typescript/packages/collapsible/**
      - typescript/packages/auto-complete-input/**
      - typescript/packages/typeahead/**
      - typescript/packages/input/**
      - typescript/packages/loading/**
      - typescript/packages/virtual-list/**
      - typescript/packages/table/**
      - typescript/packages/pagination/**
      - typescript/packages/copy-to-clipboard/**
      - typescript/packages/calculations-table/**
      - typescript/packages/title/**
      - typescript/packages/dynatic-css/**
      - typescript/packages/dynatic-css-utils/**
      - typescript/packages/syntax-highlighter/**
      - typescript/packages/parse-yaml/**
      - typescript/packages/ui-theme/**
      - typescript/packages/css-utils/**
      - typescript/packages/radio-button/**
      - typescript/packages/scrollspy-anchors/**
      - typescript/packages/breadcrumbs/**
      - typescript/packages/binary/**
      - typescript/dev-packages/dynatic-css-vite-plugin/**
      - typescript/dev-packages/dynatic-css-typescript-parser/**
      - typescript/dev-packages/typescript-file-manipulation/**
      - typescript/dev-packages/recursive-import-iteration/**
      - typescript/packages/import-parser/**
      - typescript/packages/export-parser/**
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Install Netlify CLI
        run: npm i -g netlify-cli
      - name: Install tsx
        run: npm i -g tsx@^4.7.2 --save-dev
      - name: Create _redirects file
        run: node ./ci-scripts/createCSRRedirects.js cs
      - name: Create working folder
        run: mkdir full-application
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js cs
      - name: Copy root package.json
        run: cp -r package.json ./full-application/
      - name: Copy workspace
        run: |
          mkdir -p ./full-application/apps
          cp -r ./apps/cs ./full-application/apps
      - name: Copy dependencies
        run: |
          mkdir -p ./full-application/packages
          cp -r ./packages/icons ./full-application/packages
          cp -r ./packages/mathml ./full-application/packages
          cp -r ./packages/math-parser ./full-application/packages
          cp -r ./packages/string-utils ./full-application/packages
          cp -r ./packages/regex ./full-application/packages
          cp -r ./packages/router ./full-application/packages
          cp -r ./packages/utils ./full-application/packages
          cp -r ./packages/url ./full-application/packages
          cp -r ./packages/environment ./full-application/packages
          cp -r ./packages/hooks ./full-application/packages
          cp -r ./packages/array-utils ./full-application/packages
          cp -r ./packages/object-utils ./full-application/packages
          cp -r ./packages/parse-typescript ./full-application/packages
          cp -r ./packages/sidebar ./full-application/packages
          cp -r ./packages/animation-container ./full-application/packages
          cp -r ./packages/is-dev ./full-application/packages
          cp -r ./packages/button ./full-application/packages
          cp -r ./packages/tooltip ./full-application/packages
          cp -r ./packages/randomizer ./full-application/packages
          cp -r ./packages/edge-intersection ./full-application/packages
          cp -r ./packages/element-utils ./full-application/packages
          cp -r ./packages/calculate-relative-position ./full-application/packages
          cp -r ./packages/collapsible ./full-application/packages
          cp -r ./packages/auto-complete-input ./full-application/packages
          cp -r ./packages/typeahead ./full-application/packages
          cp -r ./packages/input ./full-application/packages
          cp -r ./packages/loading ./full-application/packages
          cp -r ./packages/virtual-list ./full-application/packages
          cp -r ./packages/table ./full-application/packages
          cp -r ./packages/pagination ./full-application/packages
          cp -r ./packages/copy-to-clipboard ./full-application/packages
          cp -r ./packages/calculations-table ./full-application/packages
          cp -r ./packages/title ./full-application/packages
          cp -r ./packages/dynatic-css ./full-application/packages
          cp -r ./packages/dynatic-css-utils ./full-application/packages
          cp -r ./packages/syntax-highlighter ./full-application/packages
          cp -r ./packages/parse-yaml ./full-application/packages
          cp -r ./packages/ui-theme ./full-application/packages
          cp -r ./packages/css-utils ./full-application/packages
          cp -r ./packages/radio-button ./full-application/packages
          cp -r ./packages/scrollspy-anchors ./full-application/packages
          cp -r ./packages/breadcrumbs ./full-application/packages
          cp -r ./packages/binary ./full-application/packages
          cp -r ./dev-packages/dynatic-css-vite-plugin ./full-application/packages
          cp -r ./dev-packages/dynatic-css-typescript-parser ./full-application/packages
          cp -r ./dev-packages/typescript-file-manipulation ./full-application/packages
          cp -r ./dev-packages/recursive-import-iteration ./full-application/packages
          cp -r ./packages/import-parser ./full-application/packages
          cp -r ./packages/export-parser ./full-application/packages
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build-ga
      - name: Deploy
        run: netlify deploy --prod --dir=./apps/cs/dist
