name: Cs Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/apps/cs/**
      - typescript/packages/icons/**
      - typescript/packages/mathml/**
      - typescript/packages/math-parser/**
      - typescript/packages/string-utils/**
      - typescript/packages/regex/**
      - typescript/packages/router/**
      - typescript/packages/utils/**
      - typescript/packages/url/**
      - typescript/packages/environment/**
      - typescript/packages/hooks/**
      - typescript/packages/array-utils/**
      - typescript/packages/object-utils/**
      - typescript/packages/parse-typescript/**
      - typescript/packages/sidebar/**
      - typescript/packages/animation-container/**
      - typescript/packages/is-dev/**
      - typescript/packages/button/**
      - typescript/packages/tooltip/**
      - typescript/packages/randomizer/**
      - typescript/packages/edge-intersection/**
      - typescript/packages/element-utils/**
      - typescript/packages/calculate-relative-position/**
      - typescript/packages/collapsible/**
      - typescript/packages/auto-complete-input/**
      - typescript/packages/typeahead/**
      - typescript/packages/input/**
      - typescript/packages/loading/**
      - typescript/packages/virtual-list/**
      - typescript/packages/table/**
      - typescript/packages/pagination/**
      - typescript/packages/copy-to-clipboard/**
      - typescript/packages/calculations-table/**
      - typescript/packages/title/**
      - typescript/packages/dynatic-css/**
      - typescript/packages/dynatic-css-utils/**
      - typescript/packages/syntax-highlighter/**
      - typescript/packages/parse-yaml/**
      - typescript/packages/ui-theme/**
      - typescript/packages/css-utils/**
      - typescript/packages/radio-button/**
      - typescript/packages/scrollspy-anchors/**
      - typescript/packages/breadcrumbs/**
      - typescript/packages/binary/**
      - typescript/dev-packages/dynatic-css-vite-plugin/**
      - typescript/dev-packages/dynatic-css-typescript-parser/**
      - typescript/dev-packages/typescript-file-manipulation/**
      - typescript/dev-packages/recursive-import-iteration/**
      - typescript/packages/import-parser/**
      - typescript/packages/export-parser/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd apps/cs && npm run typecheck
