name: Detect Repository Dependencies Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/detect-repository-dependencies/**
      - typescript/packages/regex/**
      - typescript/dev-packages/paths/**
      - typescript/dev-packages/files/**
      - typescript/dev-packages/package-manager/**
      - typescript/dev-packages/detect-repository-dependencies-types/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd dev-packages/detect-repository-dependencies && npm run typecheck
