name: Docker Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/docker/**
      - typescript/dev-packages/yaml/**
      - typescript/dev-packages/packages/**
      - typescript/dev-packages/paths/**
      - typescript/dev-packages/terminal-utils/**
      - typescript/packages/utils/**
      - typescript/dev-packages/git/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd typescript/dev-packages/docker && npm run typecheck
