name: Form Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/packages/form/**
      - typescript/packages/design-patterns/**
      - typescript/packages/randomizer/**
      - typescript/packages/object-utils/**
      - typescript/packages/parse-typescript/**
      - typescript/packages/utils/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd packages/form && npm run typecheck
