name: Package Lock Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/package-lock/**
      - typescript/dev-packages/paths/**
      - typescript/dev-packages/packages/**
      - typescript/dev-packages/terminal-utils/**
      - typescript/packages/utils/**
      - typescript/dev-packages/git/**
      - typescript/dev-packages/create-typecheck-github-actions-config/**
      - typescript/dev-packages/package-json/**
      - typescript/dev-packages/files/**
      - typescript/dev-packages/package-manager/**
      - typescript/dev-packages/terminal-multi-select/**
      - typescript/dev-packages/detect-repository-dependencies/**
      - typescript/packages/regex/**
      - typescript/dev-packages/typescript-file-manipulation/**
      - typescript/packages/object-utils/**
      - typescript/packages/parse-typescript/**
      - typescript/dev-packages/detect-repository-dependencies-types/**
      - typescript/dev-packages/detect-file-changes/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd dev-packages/package-lock && npm run typecheck
