name: Recursive Dependency Iteration Typecheck
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/recursive-import-iteration/**
      - typescript/packages/import-parser/**
      - typescript/packages/string-utils/**
      - typescript/packages/regex/**
      - typescript/packages/export-parser/**
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js
      - name: Install dependencies
        run: npm i
      - name: Run typecheck
        run: cd dev-packages/recursive-import-iteration && npm run typecheck
