name: Test tests
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - typescript/dev-packages/test/**
      - typescript/dev-packages/high-precision-timing/**
jobs:
  Test-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
      - name: Remove postinstall
        run: node ./ci-scripts/removePostInstall.js cs
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: cd dev-packages/test && npm run test
